# Créer le répertoire dépot sur localhost

- name: "Saving firewall rules"
  iptable_save:
    state: present
    username: "aic"
    password: "Azerty123&"
    host: "ServerCentral"
  register: result

- debug: var=result

- name: "Create daemon script"
  daemon_script:
    username: "aic"
    password: "Azerty123&"
    host: "ServerCentral"
    IPTABLES_RULES_LIST: "{{IPTABLES_RULES_LIST}}"
    DAEMON_COMMANDS_LIST: "{{DAEMON_COMMANDS_LIST}}"
  register: result

- debug: var=result