---

- name: "Make netfilter persistent, create own logs, archive logs on remote server"
  hosts: all
  vars_prompt:
    - name: host
      prompt: "What's the hostname or the IP address of the remote machine where archive is going to be store ?"

    - name: username
      prompt: "The username to use for ssh connection ?"
      private: no

    - name: password
      prompt: "The password of this user ?"
      unsafe: yes
      private: yes

  roles:
    - role: "persistent_firewall"
      vars:
        username: {{ username }}
        password: {{ password }}
        host: {{ host }}

    - role: "firewall_logs"
    
    - role: "logs_transfer"
      vars:
        username: {{ username }}
        password: {{ password }}
        host: {{ host }}