---    
DAEMON_COMMANDS_LIST: [
  "#!/bin/sh",
  "### BEGIN INIT INFO",
  "# Provides: firewall",
  "# Required-Start: $remote_fs $syslog",
  "# Should-Start: $remote_fs $syslog",
  "# Required-Stop: $remote_fs $syslog",
  "# Should-Stop: $remote_fs $syslog",
  "# Default-Start:	2 3 4 5",
  "# Default-Stop:	 	0 1 6",
  "# Short-description: Start IPtables rules",
  "# Description: Add logs rules and restore IPtables save when the system starts",
  "### END INIT INFO",
  "# Start/stop IPtables rules",
  "#",
  "##Configuration of /etc/init.d/firewall_$hostname.sh",
  "case \"$1\" in",
  "'start')",
  "",
  "# Reset netfilter",
  "iptables -F",
  "iptables -X",
  "iptables -t nat -F",
  "iptables -t nat -X",
  "",
  "# Logs comments",
  "",
  "# Restore IPtables rules",
  "",
  "RETVAL=$?",
  ";;",
  "'stop')",
  "# Reset netfilter and load default rules",
  "iptables -t filter -F",
  "iptables -t nat -F",
  "iptables -t mangle -F",
  "iptables -t raw -F",
  "iptables -t filter -P INPUT ACCEPT",
  "iptables -t filter -P OUTPUT ACCEPT",
  "iptables -t filter -P FORWARD ACCEPT",
  "echo \"FILTER [ALL RULES .... [FLUSH] ..... POLICY ......> [ACCEPT]\"",
  "iptables -t nat -P PREROUTING ACCEPT",
  "iptables -t nat -P POSTROUTING ACCEPT",
  "iptables -t nat -P OUTPUT ACCEPT",
  "iptables -t mangle -P PREROUTING ACCEPT",
  "iptables -t mangle -P OUTPUT ACCEPT",
  "iptables -t mangle -P POSTROUTING ACCEPT",
  "iptables -t mangle -P FORWARD ACCEPT",
  "iptables -t mangle -P INPUT ACCEPT",
  "iptables -t raw -P OUTPUT ACCEPT",
  "iptables -t raw -P PREROUTING ACCEPT",
  "echo \"ALL TABLES ....[FLUSH] ..... ALL POLICY .......> [ACCEPT]\"",
  "iptables-save > /etc/firewall-client",
  "echo \"iptables-save > /etc/firewall-client .........> [OK]\"",
  "RETVAL=$?",
  ";;",
  "'restart')",
  "iptables-restore < /etc/firewall-client",
  "echo \"/etc/firewall-client ........[OK]\"",
  "RETVAL=$?",
  ";;",
  "'status')",
  "iptables -L -n --line-numbers",
  "iptables -t nat -L -n --line-numbers",
  "RETVAL=$?",
  ";;",
  "*)",
  "echo \"Usage: $0 { start | stop | restart | status }\"",
  "RETVAL=1",
  ";;",
  "esac",
  "exit $RETVAL"
  ]