- include: "crontab_config.yml"
  when: ansible_facts['os_family'] is in ["RedHat", "CentOS"] 

- name: "configure rsyslog"
  own_logs:
    state: "present"
    IPTABLES_RULES_LIST: "{{IPTABLES_RULES_LIST}}"
  notify: rsyslog restart

- name: "configure logrotate"
  logs_rotate:
    state: "present"
    LOGROTATE_LIST: "{{LOGROTATE_LIST}}"