# Créer le répertoire crontab (pb avec centOS)

- name: "Configure rsyslog"
  own_logs:
    state: "present"
    IPTABLES_RULES_LIST: "{{IPTABLES_RULES_LIST}}"
  register: result
  notify: rsyslog restart

- debug: var=result

- meta: flush_handlers

- name: "Generate IP traffic"
  ping:

- name: "Wait for log file"
  pause:
    seconds: 5
  connection: local

- name: "Configure logrotate"
  logs_rotate:
    state: "absent"
    LOGROTATE_LIST: "{{LOGROTATE_LIST}}"
  register: result
  notify: logrotate restart

- debug: var=result