- name: "Create an archiving task"
  archiving_task:
    state: "present"
  register: result

- debug: var=result

- name: "Create archiving script"
  archiving_script:
    state: "present"
    username: "aic"
    password: "Azerty123&"
    host: "ServerCentral"
    ARCHIVING_COMMANDS_LIST: "{{ARCHIVING_COMMANDS_LIST}}"
  register: result

- debug: var=result
  