---
ARCHIVING_COMMANDS_LIST: [
      "#!/bin/bash",
      "",
      "date=`date +%d_%m_%Y`",
      "month=`date +%B%Y`",
      "hostname=`hostname`",
      "",
      "echo \"Compressing logs files\"",
      "sudo tar -zcvf \"/var/log/netfilter/archive_$hostname-$date.tar.gz\" /var/log/netfilter/iptables*.1",
      "",
      "echo \"Archives transfer\"",
      "sudo rsync --remove-source-files -av -e 'ssh -i /root/.ssh/id_rsa_archiving' /var/log/netfilter/archive_$hostname-$date.tar.gz $user@$host:/LogsArchiving_REPO/$hostname/$month/"
      ]